In [32]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [38]:
df = pd.read_csv('..\\data\\processed\\regressor_to_matricula_SMART_complete.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7459 entries, 0 to 7458
Data columns (total 9 columns):
oppo_id                    7459 non-null object
asesor_id                  7459 non-null object
idcurso                    7459 non-null int64
rating                     7459 non-null object
ciudad                     7459 non-null object
pais                       7459 non-null object
tipo                       7459 non-null object
days_since_modification    7459 non-null float64
Result                     7459 non-null bool
dtypes: bool(1), float64(1), int64(1), object(6)
memory usage: 473.5+ KB

In [35]:
df['asesor_id'] = df.asesor_id.astype('category')

df['idcurso'] = df.idcurso.astype('category')
#smart['prkt_ciudades_id_c'] = smart.prkt_ciudades_id_c.astype('category')
df['prkt_paises_id1_c'] = df.prkt_paises_id1_c.astype('category')
df['ciudad'] = df.prkt_paises_id1_c.astype('category')
df['rating'] = df.rating.astype('category')
df['tipo'] = df.tipo.astype('category')
df['status'] = df.status.astype('category')
df.ciudad.fillna(method='ffill', inplace=True)

In [36]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7459 entries, 0 to 7458
Data columns (total 11 columns):
oppo_id                    7459 non-null object
status                     7459 non-null category
asesor_id                  7459 non-null category
idcurso                    7459 non-null category
rating                     7459 non-null category
prkt_paises_id1_c          7441 non-null category
tipo                       7459 non-null category
Result                     7459 non-null bool
days_since_modification    7459 non-null float64
ciudad                     7459 non-null category
nivel_educativo            7459 non-null object
dtypes: bool(1), category(7), float64(1), object(2)
memory usage: 242.9+ KB

In [37]:
df.prkt_paises_id1_c.value_counts()

EC    3754
CO    2294
ES     625
PE     140
MX     105
CR      62
AR      61
DO      52
VE      49
SV      47
CL      26
PY      25
GT      23
BO      22
US      18
UY      17
DE      15
NI      14
IE       9
HN       8
BR       8
PA       7
CH       6
CU       5
PT       4
GB       3
AD       3
DK       3
AO       3
NL       3
FR       3
HT       3
AU       2
GQ       2
PR       2
CA       2
AE       1
ZA       1
CV       1
CZ       1
ET       1
IL       1
IT       1
JM       1
JP       1
KR       1
LU       1
MZ       1
PL       1
RU       1
SN       1
0        1
Name: prkt_paises_id1_c, dtype: int64

,oppo_id,education_level_c,status,asesor_id,idcurso,rating,prkt_paises_id1_c,tipo,Result,days_since_modification,ciudad
464,ff1babf2-6a87-11e9-aecc-005056ab32f0,licenciado,asignado,dcf0d74b-f693-27e5-12d1-577100d3b8d4,138762,B,NaN,POSTP,False,7.267650,NaN
891,f11c6a94-1e3f-11e9-bef6-005056ab32f0,graduado,volver_duplicado,a8a08b2a-f48c-11e7-b3e4-005056ab32f0,130999,A,NaN,POSTU,False,100.467465,NaN
1432,e05b657a-390b-11e9-a8ec-005056ab32f0,profesional_licenciado,descartado_no_duplicado,4e4d572a-2ce5-13bf-53aa-577105fa5b10,19921,C,NaN,POSTU,False,48.308472,NaN
1664,3a9bf87c-0466-11e9-bc6b-005056ab32f0,licenciado,volver_duplicado,7b130dae-fe22-11e8-b1be-005056ab32f0,19921,D,NaN,POSTU,False,115.992373,NaN
1683,04b71dd8-030b-11e9-b050-005056ab32f0,licenciado,volver_duplicado,7df28d53-3451-f623-4c78-594b73bf2611,115361,C,NaN,POSTU,False,115.992373,NaN
1841,1af802cc-2ea5-11e9-a70c-005056ab32f0,tercer_nivel,interesado_no_tiempo,f375d686-5839-fe1e-cd2a-577105cbbea7,19921,C,NaN,POSTU,False,64.519039,NaN
2183,66d3b568-09e5-11e9-a832-005056ab32f0,tercer_nivel,interesado_no_no_puede_pagarlo,7b130dae-fe22-11e8-b1be-005056ab32f0,115361,A,NaN,POSTU,False,114.206852,NaN
2488,246ee718-2733-11e9-88a6-005056ab32f0,licenciado,matricula_realizada_baja,4a2cf3ee-fe22-11e8-9218-005056ab32f0,19921,B,NaN,POSTU,False,34.321759,NaN
2542,d9248012-2fd7-11e9-9c4a-005056ab32f0,ingeniero_profesional,interesado_no_academico,878ded9f-ae7c-7606-bf5b-5857a7641cad,115361,A,NaN,POSTU,False,70.278495,NaN
3022,66bc76f6-16cd-11e9-9ff8-005056ab32f0,graduado,volver_duplicado,a8a08b2a-f48c-11e7-b3e4-005056ab32f0,133499,A,NaN,POSTU,False,100.467465,NaN
3528,bca77f7c-4b19-11e9-8543-005056ab32f0,ingeniero,interesado_no_caro,7df28d53-3451-f623-4c78-594b73bf2611,19921,D,NaN,POSTU,False,37.319757,NaN
4603,358b1ba4-4180-11e9-ba1f-005056ab32f0,tercer_nivel,volver_duplicado,89401563-b718-5c20-bd00-5761bab5fd4d,19921,D,NaN,POSTU,False,69.620266,NaN
4838,a6ba9d8e-116c-11e9-90e4-005056ab32f0,postgrado,envio_formulario_admision,7b130dae-fe22-11e8-b1be-005056ab32f0,19921,D,NaN,POSTU,False,112.120556,NaN
5195,385f9ece-0092-11e9-b071-005056ab32f0,tercer_nivel,descartado_no_localizable,d1d8e77c-8d85-170d-bc28-595cae49fc1f,19921,C,NaN,POSTU,False,111.400764,NaN
5824,1e22f81e-db97-11e8-8230-005056ab32f0,tecnico_tecnologo,volver_duplicado,263db3dc-a673-2505-0e00-577105802443,19921,C,NaN,POSTU,False,116.002106,NaN
6731,10179276-1fd9-11e9-bd3c-005056ab32f0,diplomado,interesado_no_no_puede_pagarlo,6f21f354-8102-11e8-8588-005056ab32f0,19921,C,NaN,POSTU,False,101.190301,NaN
6779,06f8e876-2938-11e9-b2a5-005056ab32f0,tercer_nivel,volver_ilocalizable,521c9c38-90c4-11e8-84c2-005056ab32f0,133499,C,NaN,POSTU,False,41.359583,NaN
7313,6652c05a-4718-11e9-a14a-005056ab32f0,tercer_nivel,tlf_no_valido,4a2cf3ee-fe22-11e8-9218-005056ab32f0,19921,D,NaN,POSTU,False,62.369734,NaN

In [47]:
df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
...                    'num_wings': [2, 0, 0, 0],
...                    'num_specimen_seen': [10, 2, 1, 8]},
...                   index=['falcon', 'dog', 'spider', 'fish'])

In [48]:
df.sample(n = 20, replace = False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [58]:
from sklearn.metrics import log_loss
import numpy as np

In [77]:
y_pre = np.array([0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.99999999])
y_real = np.array([1,1,1,1,1,1,1,1,1,0])
log_loss(y_real,y_pre )

1.9368925379848043

In [56]:
import keras

ModuleNotFoundError: No module named 'keras'

In [55]:
keras.losses.binary_crossentropy(y_true, y_pred)

NameError: name 'keras' is not defined